spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: bookmsid
          uri: lb://bookms
          predicates: 
            - Path=/bookms/**
          filters:
            - RewritePath=/bookms/(?<path>.*),/$\{path}
        - id: issuemsid
          uri: lb://issuems
          predicates: 
            - Path=/issuems/**
          filters:
            - RewritePath=/issuems/(?<path>.*),/$\{path}
server:
  port: 8080
management:
  health:
    circuitbreakers:
      enabled : true
  endpoint:
    health: 
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/