version: '3.7'

services:
  eureka-server:
    image: eureka-server:1.0
    container_name: eureka-server
    ports:
      - "8761:8761"   
    networks:
      - eureka-network

  bookms:
    container_name: bookms
    image: bookms:1.0   
    ports:
      - "8082:8082"
    networks:
      - eureka-network
    depends_on:
      - eureka-server


  issuems:
    image: issuems:1.0
    container_name: issuems
    ports:
      - "8083:8083"    
    networks:
      - eureka-network
    depends_on:
      - eureka-server
      - bookms 

  apigateway:
    image: apigateway:1.0
    container_name: apigateway
    ports:
      - "8080:8080" 
    networks:
      - eureka-network
    depends_on:
      - eureka-server
      - bookms
      - issuems
      - auth-server
 
  auth-server:
    image: auth-server:1.0
    container_name: auth-server
    ports:
       - "9000:9000"
    networks:	
      - eureka-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: [
           "--config.file=/etc/prometheus/prometheus.yml"
		   
             ]
    networks:	
      - eureka-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - eureka-network
 
networks:
  eureka-network: